### ISSUE TITLE
Question on how to preprocess the AFDB

### ISSUE THREAD

**Issue by EunhoRoh** [vishaln15/OptimizedArrhythmiaDetection#1]
Hello! I am a college student majoring in computer science engineering.
I am trying to make train data of deep learning model using MIT-BIH Atrial Fibrillation DataBase.
Could you please tell me how you labeled the symptoms of atrial fibrillation and extracted the R peak from the AFDB?
Also, how did you know that the extracted R peak had atrial fibrillation symptoms?
Finally, may I request the train data and the source code that preprocesses the AFDB?
Your answer will be of great help to me.

**Comment by vishaln15** [comment]
Hi @EunhoRoh, you can use `wfdb.rdann(PATH, 'atr')` to extract the annotations, and then use that `annotation.aux_note` to extract the `rhythm`. Furthermore, you can use that rhythm to check if that particular `rhythm[i] == '(AFIB\x00'`.  You can read the purpose of `\x00` in this [link](https://stackoverflow.com/questions/5954538/what-does-x00-mean-in-binary-file).

You can use this [link](https://archive.physionet.org/physiobank/annotations.shtml) to view the different annotations and how to read them. 

Kindly read our [paper](https://arxiv.org/pdf/2111.11789.pdf) to understand how exactly we labelled a row as a positive class (which contains Atrial Fibrillation symptoms).

Unfortunately, we lost our source code file that reads these `.atr` files. But I urge you to use the above mentioned functions as we successfully used it to perform our research.
